version: "3.8"

networks:
  cityhelp-net:
    driver: bridge

services:
  api:
    image: ${DOCKERHUB_REPO}:latest
    container_name: api
    restart: unless-stopped
    ports:
      - "2020:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./config/appsettings.json:/app/appsettings.json:ro
    networks:
      - cityhelp-net
