version: '3.8'

services:
  api:
    image: api-csharp
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "2020:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
        