version: '3.8'

services:
  api:
    image: api-csharp
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sapi
    restart: unless-stopped
    ports:
      - "2020:8080"
