name: Deploy API to Server

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate auto version
        run: echo "IMAGE_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:latest \
                       -t ${{ secrets.DOCKERHUB_REPO }}:${IMAGE_VERSION} \
                       -f docker/Dockerfile .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest
          docker push ${{ secrets.DOCKERHUB_REPO }}:${IMAGE_VERSION}

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKERHUB_REPO=${{ secrets.DOCKERHUB_REPO }}

            cd ${{ secrets.SERVER_PROJECT_PATH }}
            
            # Sobrescribe todo el repositorio local
            git fetch --all
            git reset --hard origin/main

            # Detiene contenedores actuales
            docker compose -f docker/docker-compose.yml down || true

            # Descarga la Ãºltima imagen del repositorio remoto
            docker pull $DOCKERHUB_REPO:latest

            # Levanta contenedores con la imagen descargada
            docker compose -f docker/docker-compose.yml up -d --force-recreate
