name: Test SSH connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "CONEXIÃ“N EXITOSA"
            hostname
            whoami
            pwd
